repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: debug-statements
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        args: ["--workers=1"]
        language_version: python3.14
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
